# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WebStoreProject' do
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebStoreProject

  target 'WebStoreProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WebStoreProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
